version: '3'
services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes: 
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=mysecretpassword

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
     - .:/app
     - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    user: 1000:1000

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes: 
     - .:/app
     - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis

volumes:
  bundle:
  postgres:
  redis:
